[package]
name = "matmult"
version = "0.2.0"
authors = ["Théophile Ranquet <theophile.ranquet@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.8", features = [ "derive" ] }
rand = "0.7"
